tap "fluxcd/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "yt-dlp/taps"
brew "ack"
brew "aha"
brew "python@3.9"
brew "awscli"
brew "glib"
brew "doctl"
brew "dos2unix"
brew "libtool"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "openjpeg"
brew "libass"
brew "ffmpeg"
brew "fswatch"
brew "gh"
brew "graphviz"
brew "helm"
brew "kubeseal"
brew "lazygit"
brew "libslirp"
brew "mas"
brew "maven"
brew "minikube"
brew "node"
brew "nvm"
brew "octant"
brew "qemu"
brew "podman"
brew "pyenv"
brew "python@3.10"
brew "terraform"
brew "thefuck"
brew "tree"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "fluxcd/tap/flux"
brew "yt-dlp/taps/yt-dlp"
mas "Be Focused", id: 973134470
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "QuickShade", id: 931571202
mas "Telegram", id: 747648890
mas "Trello", id: 1278508951
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
