# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
  
  - trigger: ":warn"
    replace: "⚠️"

  - trigger: ":check"
    replace: "✅"

  - trigger: ":cross"
    replace: "❌"
  
  - trigger: ":fail"
    replace: "❌"

  - trigger: ":think"
    replace: "🤔"

  - trigger: ":?"
    replace: "🤷‍♂️"

  - trigger: ":cljs"
    replace: "console.log(JSON.stringify())"

  - trigger: ":hmm"
    replace: "🤔"

  - trigger: ":alert"
    replace: "🚨"

  - trigger: ":bell"
    replace: "🚨"

  - trigger: ":party"
    replace: "🎉"

  - trigger: "]ok"
    replace: "👌"

  - trigger: ":sun"
    replace: "☀️"

  - trigger: ":wave"
    replace: "👋"

  - trigger: ":smile"
    replace: "😀"
  
  - trigger: ":morning"
    replace: "🌅"

  - trigger: ":love"
    replace: "❤️"

  - trigger: ":1038"
    replace: "103879u@gmail.com"
  
  - trigger: "jawx"
    replace: "joel.limjing@airwallex.com"

  - trigger: "pmd"
    replace: "promt.md"

  - trigger: ":fdate"
    replace: "{{year}} {{month_name}} {{day}} {{yyyymmdd}}"
    vars:
      - name: year
        type: date
        params:
          format: "%Y"
      - name: month_name
        type: date
        params:
          format: "%B"
      - name: day
        type: date
        params:
          format: "%d"
      - name: yyyymmdd
        type: date
        params:
          format: "%Y%mm%d"

  - trigger: ":sdate"
    replace: "{{yyyymmdd}}"
    vars:
      - name: yyyymmdd
        type: date
        params:
          format: "%Y%m%d"

  - trigger: ":ddate"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H%M"

  # And much more! For more information, visit the docs: https://espanso.org/docs/